# Generated by Django 6.0.2 on 2026-03-05 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_gender_order_feedback_phonelisting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_report', to='core.phonelisting'),
        ),
    ]
