# Generated by Django 6.0.2 on 2026-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testreport_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='testreport',
            name='functional_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='valuation_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
